#define VERSION_STRING "@VERSION@"
#define VERSION_RC @VERSION_Y@,@VERSION_M@,@VERSION_D@,@VERSION_B@
#define VERSION_Y @VERSION_Y@
#define VERSION_M @VERSION_M@
#define VERSION_D @VERSION_D@
#define VERSION_B @VERSION_B@